// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bjpezohjzktqpvfhdutb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJqcGV6b2hqemt0cXB2ZmhkdXRiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwNzk0MDMsImV4cCI6MjA3MDY1NTQwM30.L52z5uCuDrLJmnq8m4BVJkGl4PZGUupQbVqx-lWkwS8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});